name: "1.1) Print Version: Simple"

on: [push]

jobs:
  print-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Display Python version
        run: python --version
