name: "1.3) Run .py Scripts"

on: [push]

jobs:
  print-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Display Python version (BASH script)
        run: python --version

      - name: Display Python version (Python script)
        shell: python
        run: |
          import os
          os.system('python --version')

      - name: Display Python version (script from file)
        run: python .github/print-python-version.py 

      - name: Display Contents of tox.ini file (Python script)
        shell: python
        run: print(open('tox.ini', 'r').read())

      - name: Display Contents of Make file (script from file)
        run: python .github/print-makefile.py 
